steps:
  - name: node:16.0.0
    entrypoint: npm
    args: ['install']

  - name: node:16.0.0
    entrypoint: npm
    args: ["run","create-env"]
    env:
      - 'PORT=${_PORT}'
      - 'HOST=${_HOST}'
      - 'FIREBASE_APIKEY=${_FIREBASE_APIKEY}'
      - 'FIREBASE_APIKEY=${_FIREBASE_APIKEY}'
      - 'FIREBASE_PROJECTID=${_FIREBASE_PROJECTID}'
      - 'FIREBASE_STORAGEBUCKET=${_FIREBASE_STORAGEBUCKET}'
      - 'FIREBASE_MESSAGINGSENDERID=${_FIREBASE_MESSAGINGSENDERID}'
      - 'FIREBASE_APPID=${_FIREBASE_APPID}'
      - 'FIREBASE_MEASUREMENTID=${_FIREBASE_MEASUREMENTID}'

  - name: node:16.0.0
    entrypoint: npm
    args: ["run",'start']

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
