steps:

  - name: node:16.0.0
    entrypoint: yarn
    args: ['install']

  - name: node:16.0.0
    entrypoint: yarn
    args: ["run","create-env"]
    env:
      - 'PORT=${_PORT}'
      - 'HOST=${_HOST}'
      - 'FIREBASE_APIKEY=${_FIREBASE_APIKEY}'
      - 'FIREBASE_APIKEY=${_FIREBASE_APIKEY}'
      - 'FIREBASE_PROJECTID=${_FIREBASE_PROJECTID}'
      - 'FIREBASE_STORAGEBUCKET=${_FIREBASE_STORAGEBUCKET}'
      - 'FIREBASE_MESSAGINGSENDERID=${_FIREBASE_MESSAGINGSENDERID}'
      - 'FIREBASE_APPID=${_FIREBASE_APPID}'
      - 'FIREBASE_MEASUREMENTID=${_FIREBASE_MEASUREMENTID}'

  # Fetch the secret from Secret Manager and store it as a file
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          gcloud secrets versions access latest --secret="firebase_key" > /workspace/src/serviceAccount.json

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          gcloud secrets versions access latest --secret="gcs_key" > /workspace/src/serviceAccountCloudStorage.json

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          gcloud secrets versions access latest --secret="app_engine_key" > /workspace/src/serviceAccountGAE.json

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          gcloud app deploy --service-account=cloudbuilder@trashcash-project.iam.gserviceaccount.com

